version: "3"
services:
  idp:
    image: quay.io/keycloak/keycloak:19.0.3-legacy
    container_name: keycloak
    volumes:
      - ./keycloak-rest-repo/target/keycloak-rest-repo.jar:/opt/jboss/keycloak/standalone/deployments/keycloak-rest-repo.jar
      - ./keycloak-custom-authenticator/target/keycloak-custom-authenticator.jar:/opt/jboss/keycloak/standalone/deployments/keycloak-custom-authenticator.jar
    restart: always
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      JAVA_OPTS_APPEND: -Dkeycloak.profile.feature.admin2=disabled
    ports:
      - 8080:8080

  mmock:
    container_name: mmock
    image: jordimartin/mmock
    restart: always
    volumes:
      - ./mmock-config/:/config/
    ports:
      - 8082:8082
      - 8083:8083